'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace JSONandXMLVb
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Member", [Namespace]:="http://sametcelikbicak.com/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Member
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        Private SalaryField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PositionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Salary() As Integer
            Get
                Return Me.SalaryField
            End Get
            Set
                If (Me.SalaryField.Equals(value) <> true) Then
                    Me.SalaryField = value
                    Me.RaisePropertyChanged("Salary")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Position() As String
            Get
                Return Me.PositionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PositionField, value) <> true) Then
                    Me.PositionField = value
                    Me.RaisePropertyChanged("Position")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://sametcelikbicak.com/", ConfigurationName:="JSONandXMLVb.JSONandXMLSoap")>  _
    Public Interface JSONandXMLSoap
        
        'CODEGEN: Generating message contract since element name GetTeamFromXMLResult from namespace http://sametcelikbicak.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://sametcelikbicak.com/GetTeamFromXML", ReplyAction:="*")>  _
        Function GetTeamFromXML(ByVal request As JSONandXMLVb.GetTeamFromXMLRequest) As JSONandXMLVb.GetTeamFromXMLResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://sametcelikbicak.com/GetTeamFromXML", ReplyAction:="*")>  _
        Function GetTeamFromXMLAsync(ByVal request As JSONandXMLVb.GetTeamFromXMLRequest) As System.Threading.Tasks.Task(Of JSONandXMLVb.GetTeamFromXMLResponse)
        
        'CODEGEN: Generating message contract since element name GetTeamFromJSONResult from namespace http://sametcelikbicak.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://sametcelikbicak.com/GetTeamFromJSON", ReplyAction:="*")>  _
        Function GetTeamFromJSON(ByVal request As JSONandXMLVb.GetTeamFromJSONRequest) As JSONandXMLVb.GetTeamFromJSONResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://sametcelikbicak.com/GetTeamFromJSON", ReplyAction:="*")>  _
        Function GetTeamFromJSONAsync(ByVal request As JSONandXMLVb.GetTeamFromJSONRequest) As System.Threading.Tasks.Task(Of JSONandXMLVb.GetTeamFromJSONResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTeamFromXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTeamFromXML", [Namespace]:="http://sametcelikbicak.com/", Order:=0)>  _
        Public Body As JSONandXMLVb.GetTeamFromXMLRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JSONandXMLVb.GetTeamFromXMLRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetTeamFromXMLRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTeamFromXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTeamFromXMLResponse", [Namespace]:="http://sametcelikbicak.com/", Order:=0)>  _
        Public Body As JSONandXMLVb.GetTeamFromXMLResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JSONandXMLVb.GetTeamFromXMLResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://sametcelikbicak.com/")>  _
    Partial Public Class GetTeamFromXMLResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTeamFromXMLResult() As JSONandXMLVb.Member
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTeamFromXMLResult() As JSONandXMLVb.Member)
            MyBase.New
            Me.GetTeamFromXMLResult = GetTeamFromXMLResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTeamFromJSONRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTeamFromJSON", [Namespace]:="http://sametcelikbicak.com/", Order:=0)>  _
        Public Body As JSONandXMLVb.GetTeamFromJSONRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JSONandXMLVb.GetTeamFromJSONRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetTeamFromJSONRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTeamFromJSONResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTeamFromJSONResponse", [Namespace]:="http://sametcelikbicak.com/", Order:=0)>  _
        Public Body As JSONandXMLVb.GetTeamFromJSONResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JSONandXMLVb.GetTeamFromJSONResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://sametcelikbicak.com/")>  _
    Partial Public Class GetTeamFromJSONResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTeamFromJSONResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTeamFromJSONResult As String)
            MyBase.New
            Me.GetTeamFromJSONResult = GetTeamFromJSONResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface JSONandXMLSoapChannel
        Inherits JSONandXMLVb.JSONandXMLSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class JSONandXMLSoapClient
        Inherits System.ServiceModel.ClientBase(Of JSONandXMLVb.JSONandXMLSoap)
        Implements JSONandXMLVb.JSONandXMLSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JSONandXMLVb_JSONandXMLSoap_GetTeamFromXML(ByVal request As JSONandXMLVb.GetTeamFromXMLRequest) As JSONandXMLVb.GetTeamFromXMLResponse Implements JSONandXMLVb.JSONandXMLSoap.GetTeamFromXML
            Return MyBase.Channel.GetTeamFromXML(request)
        End Function
        
        Public Function GetTeamFromXML() As JSONandXMLVb.Member()
            Dim inValue As JSONandXMLVb.GetTeamFromXMLRequest = New JSONandXMLVb.GetTeamFromXMLRequest()
            inValue.Body = New JSONandXMLVb.GetTeamFromXMLRequestBody()
            Dim retVal As JSONandXMLVb.GetTeamFromXMLResponse = CType(Me,JSONandXMLVb.JSONandXMLSoap).GetTeamFromXML(inValue)
            Return retVal.Body.GetTeamFromXMLResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JSONandXMLVb_JSONandXMLSoap_GetTeamFromXMLAsync(ByVal request As JSONandXMLVb.GetTeamFromXMLRequest) As System.Threading.Tasks.Task(Of JSONandXMLVb.GetTeamFromXMLResponse) Implements JSONandXMLVb.JSONandXMLSoap.GetTeamFromXMLAsync
            Return MyBase.Channel.GetTeamFromXMLAsync(request)
        End Function
        
        Public Function GetTeamFromXMLAsync() As System.Threading.Tasks.Task(Of JSONandXMLVb.GetTeamFromXMLResponse)
            Dim inValue As JSONandXMLVb.GetTeamFromXMLRequest = New JSONandXMLVb.GetTeamFromXMLRequest()
            inValue.Body = New JSONandXMLVb.GetTeamFromXMLRequestBody()
            Return CType(Me,JSONandXMLVb.JSONandXMLSoap).GetTeamFromXMLAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JSONandXMLVb_JSONandXMLSoap_GetTeamFromJSON(ByVal request As JSONandXMLVb.GetTeamFromJSONRequest) As JSONandXMLVb.GetTeamFromJSONResponse Implements JSONandXMLVb.JSONandXMLSoap.GetTeamFromJSON
            Return MyBase.Channel.GetTeamFromJSON(request)
        End Function
        
        Public Function GetTeamFromJSON() As String
            Dim inValue As JSONandXMLVb.GetTeamFromJSONRequest = New JSONandXMLVb.GetTeamFromJSONRequest()
            inValue.Body = New JSONandXMLVb.GetTeamFromJSONRequestBody()
            Dim retVal As JSONandXMLVb.GetTeamFromJSONResponse = CType(Me,JSONandXMLVb.JSONandXMLSoap).GetTeamFromJSON(inValue)
            Return retVal.Body.GetTeamFromJSONResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JSONandXMLVb_JSONandXMLSoap_GetTeamFromJSONAsync(ByVal request As JSONandXMLVb.GetTeamFromJSONRequest) As System.Threading.Tasks.Task(Of JSONandXMLVb.GetTeamFromJSONResponse) Implements JSONandXMLVb.JSONandXMLSoap.GetTeamFromJSONAsync
            Return MyBase.Channel.GetTeamFromJSONAsync(request)
        End Function
        
        Public Function GetTeamFromJSONAsync() As System.Threading.Tasks.Task(Of JSONandXMLVb.GetTeamFromJSONResponse)
            Dim inValue As JSONandXMLVb.GetTeamFromJSONRequest = New JSONandXMLVb.GetTeamFromJSONRequest()
            inValue.Body = New JSONandXMLVb.GetTeamFromJSONRequestBody()
            Return CType(Me,JSONandXMLVb.JSONandXMLSoap).GetTeamFromJSONAsync(inValue)
        End Function
    End Class
End Namespace
